name: server CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 

      uses: actions/setup-node@v2
      with: 
        node-version: "16.x"

    - name: Install dependencies
      run: npm install
